// Graphics for the Nation Stats puzzle - that lists country population and area stats and then
// a visualization (generated by this program) of a few countries population and areas. The solver
// has to identify and label the country, and then read off the answer by picking off specific
// letters from each identified country.
void setup() {
  noLoop();
  size(1000, 1000);
  String names[] = {
    "A--", // 0
    "-B-", // 1
    "--C"  // 2
  };
  int populations[] = {
    100,
    200,
    300
  };
  int areas[] = {
    400,
    500,
    600
  };
  NationStatHelper helper = new NationStatHelper(names, populations, areas);
  int puzzleIndex = 0; // Ranges fro 0-4 to pick the appropriate puzzle.
  // IDs(indices) of chosen countries for visualization, in order.
  int[][] chosenCountryLists = {
    {0,1, 2}
  };
  // List of answers, one per puzzle.
  String[] answers = {
    "ABC"
  };
  
  helper.renderPuzzle(chosenCountryLists[puzzleIndex], answers[puzzleIndex]);
  println("PUZZLE ID: " + (puzzleIndex+1));
  println("ANSWER: " + answers[puzzleIndex]);
  save("output\\nationStats"+(puzzleIndex+1)+".png");
}