// Graphics for the Nation Stats puzzle - that lists country population and area stats and then
// a visualization (generated by this program) of a few countries population and areas. The solver
// has to identify and label the country, and then read off the answer by picking off specific
// letters from each identified country.


void setup() {
  noLoop();
  size(800, 600);
  Country[] countries = {
    new Country("China", 1336718015, 3705386), 
    new Country("India", 1189172906, 1269338), 
    new Country("USA", 313232044, 3718691), 
    new Country("Indonesia", 245613043, 741096), 
    new Country("Brazil", 203429773, 3286470), 
    new Country("Pakistan", 187342721, 310401), 
    new Country("Bangladesh", 158570535, 55598), 
    new Country("Nigeria", 155215573, 356667), 
    new Country("Russia", 138739892, 6592735), 
    new Country("Japan", 126475664, 145882), 
    new Country("Mexico", 113724226, 761602), 
    new Country("Philippines", 101833938, 115830)
  };

  NationStatHelper helper = new NationStatHelper(countries);
  int puzzleIndex = 0; // Ranges fro 0-4 to pick the appropriate puzzle.
  // IDs(indices) of chosen countries for visualization, in order.

  String[][] chosenCountryLists = {
    { "CHIN>A", "IN>DIA", "U>SA" }
  };

  String[]chosenCountries  = chosenCountryLists[puzzleIndex];
  String answer = helper.computeAnswer(chosenCountries);
  Table stats = helper.renderPuzzle(chosenCountries);
  String prefix = "output\\nationStats"+(puzzleIndex+1);
  String imgFileName = prefix+".png";
  String statsFileName = prefix + ".csv";
  
  println("PUZZLE ID: " + (puzzleIndex+1));
  println("ANSWER: " + answer);
  println("IMAGE SAVED TO: " + imgFileName);
  println("STATS SAVED TO: " + statsFileName);

  save(imgFileName);
  saveTable(stats, statsFileName);
}