

int[][] puzzlesByGuild = {

  //Guild1:
  {886, 803, 887, 881, 684, 203, 288, 550, 328, 565}, 

  //Guild2:
  {107, 118, 590, 765, 394, 683, 183, 428, 302, 381}, 

  //Guild3:
  {193, 852, 892, 540, 292, 217, 199, 600, 111, 613}, 

  //Guild4:
  {489, 240, 650, 585, 664, 860, 138, 871, 721, 705}, 

  //Guild5:
  {319, 884, 609, 101, 578, 408, 343, 794, 403}, // Just nine.

  //Guild6:
  {350, 686, 347, 537, 725, 456, 366, 696, 788} // just nine for now.

};

String[] tickets = {
  // Generated by admin-stuff.pde Processing script
  // on Nov 16th 2015 with seed=128
  "TKO", "BQF", "KTF", "VFB", "IRT", "WEJ", "MJQ", "JDB", "HTE", "NRE", 
  "UYA", "FPK", "PBG", "LWE", "UIQ", "LPN", "FKA", "ZHZ", "IWK", "FMX", 
  "LGO", "KWU", "WCY", "ZKV", "OHN", "WFZ", "AGA", "LVF", "CFE", "LGU", 
  "JKX", "OUL", "NDM", "BHT", "SOG", "WCF", "IKH", "RSK", "TEY", "TBP", 
  "FBZ", "TOT", "PTD", "KNJ", "THQ", "XSW", "ANC", "IXZ", "PWE", "FPO", 
  "OGT", "OYF", "ULJ", "MTA", "QAC", "UQE", "DJP", "TMS", "DPC", "RQU", 
  "BCY", "JVT", "ZLL", "BTL", "VZJ", "MAG", "RXF", "NAW", "QFH", "VGT", 
  "EEL", "BLA", "DMA", "WLC", "KRP", "PMU", "CYT", "GFS", "XKQ", "TQH", 
  "TNU", "OLZ", "VJE", "AYR", "UOC", "DQM", "NSK", "JEL", "FWP", "GDK", 
  "LFT", "FEU", "LRH", "OFC", "YSE", "SHQ", "BAG", "LIL", "BDW", "MZH"
};

String[] challengeNames =
  {
  "Impromptu Skit", 
  "Landmarks", 
  "Go Botany", 
  "Voluminous", 
  "Win in a min", 
  "Drawing", 
  "Builder"
};


int[] challengeIndices = {
  0, // special one - skit, just has one.
  1, 1, 1,
  2, 2, 2,
  3, 3, 3,
  4, 4, 4,
  5, 5, 5,
  6, 6, 6
};

int[] questIndices = {
  //We specify this order so that each guild is
  // assigned consequetive quests...
  0, 2, 4, 6, 8, 10,
  1, 3, 5, 7, 9, 11
};