String[] g_clanNames =  {  "Bear", "Orca", "Osprey", "Raven", "Wolf"};

String[] g_activityNames = {
  "Quest 1", 
  "Quest 2", 
  "Quest 3", 
  "Quest 4", 
  "Quest 5", 
  "Quest 6", 
  "Quest 7", 
  "Quest 8", 
  "Quest 9", 
  "Quest 10", 
  "Quest 11", 
  "Quest 12", 
  "Perspective 1", 
  "Perspective 2", 
  "Perspective 3", 
  "Perspective 4", 
  "Perspective 5", 
  "Describe it", 
  "Describe it", 
  "Dibujar", 
  "Dibujar", 
  "Furniture Factory", 
  "Furniture Factory", 
  "Voluminous", 
  "Voluminous"
};

String[][] g_puzzleData = {
  {"860", "Tile World I"}, 
  {"288", "Tile World II"}, 
  {"683", "Tile World III"}, 
  {"199", "Tile World IV"}, 
  {"138", "Tile World V"}, 
  {"343", "Count Cells I"}, 
  {"456", "Count Cells II"}, 
  {"565", "Count Cells III"}, 
  {"381", "Count Cells IV"}, 
  {"613", "Count Cells V"}, 
  {"705", "Gears I"}, 
  {"403", "Gears II"}, 
  {"788", "Gears III"}, 
  {"684", "Gears IV"}, 
  {"765", "Gears V"}, 
  {"292", "Nation Stats I"}, 
  {"585", "Nation Stats II"}, 
  {"609", "Nation Stats III"}, 
  {"347", "Nation Stats IV"}, 
  {"540", "Nation Stats V"}, 
  {"193", "Expeditions I"}, 
  {"578", "Expeditions II"}, 
  {"725", "Expeditions III"}, 
  {"366", "Expeditions IV"}, 
  {"302", "Expeditions V"}, 
  {"408", "Characteristics Matter I"}, 
  {"590", "Characteristics Matter II"}, 
  {"887", "Characteristics Matter III"}, 
  {"886", "Characteristics Matter IV"}, 
  {"803", "Characteristics Matter V"}, 
  {"118", "Constitutional Logic I"}, 
  {"852", "Constitutional Logic II"}, 
  {"240", "Constitutional Logic III"}, 
  {"319", "Constitutional Logic IV"}, 
  {"350", "Constitutional Logic V"}, 
  {"203", "Numeric Justice I"}, 
  {"394", "Numeric Justice II"}, 
  {"217", "Numeric Justice III"}, 
  {"664", "Numeric Justice IV"}, 
  {"101", "Numeric Justice V"}, 
  {"537", "EAS Involvement I"}, 
  {"107", "EAS Involvement II"}, 
  {"871", "EAS Involvement III"}, 
  {"550", "EAS Involvement IV"}, 
  {"183", "EAS Involvement V"}, 
  {"600", "Con-cent-ric I"}, 
  {"328", "Con-cent-ric II"}, 
  {"428", "Con-cent-ric III"}, 
  {"111", "Con-cent-ric IV"}, 
  {"721", "Con-cent-ric V"}
};